version: "3.9"
    
services:
  db:
    image: mariadb
    restart: always
    ports:
        - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    
  admin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8080:80"
    restart: always
    depends_on:
      - db


